# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
pilot1 = Pilot.create(name:'James T. Kirk', rank: 'Captain')
pilot2 = Pilot.create(name:'Thomas Cook', rank: 'Captain')
pilot3 = Pilot.create(name:'Roy Rogers', rank: 'Captain')
pilot4 = Pilot.create(name:'John McCain', rank: 'Captain')
pilot5 = Pilot.create(name:'Lebron Jame', rank: 'Captain')
pilot6 = Pilot.create(name:'Steve McQueen', rank: 'Captain')
pilot7 = Pilot.create(name:'John Phillips', rank: 'Captain')
pilot8 = Pilot.create(name:'Vladimir Putin', rank: 'Captain')
pilot9 = Pilot.create(name:'Barack Obama', rank: 'Captain')
pilot10 = Pilot.create(name:'America', rank: 'Captain')
pilot11 = Pilot.create(name:'Hook', rank: 'Captain')
pilot12 = Pilot.create(name:'Johnny Cash', rank: 'Captain')
pilot13 = Pilot.create(name:'Trent Reznor', rank: 'Captain')
pilot14 = Pilot.create(name:'Peter Gabriel', rank: 'Captain')


destination1 = Destination.create(name: 'San Antonio')
destination2 = Destination.create(name: 'Las Vegas')
destination3 = Destination.create(name: 'Los Angeles')
destination4 = Destination.create(name: 'Paris, France')
destination5 = Destination.create(name: 'London, England')
destination6 = Destination.create(name: 'Houston')
destination7 = Destination.create(name: 'Dallas')
destination8 = Destination.create(name: 'New York')
destination9 = Destination.create(name: 'Boston')
destination10 = Destination.create(name: 'Rome, Italy')
destination11 = Destination.create(name: 'Cape Town, South Africa')
destination12 = Destination.create(name: 'San Fransico')
destination13 = Destination.create(name: 'Seattle')
destination14 = Destination.create(name: 'Mexico City, Mexico')
destination15 = Destination.create(name: 'Instanbul, Turkey')
destination16 = Destination.create(name: 'Atlanta')
destination17 = Destination.create(name: 'Moscow, Russia')
destination18 = Destination.create(name: 'Madrid, Spain')
destination19 = Destination.create(name: 'Miami')
destination20= Destination.create(name: 'Washingtin D.C')
destination21 = Destination.create(name: 'Denver')